-- Dữ liệu huấn luyện mẫu (1000 dòng)
-- Batch 1: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Tình cảm', 'toi', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Hài', 'chieu', 'duoi_18', 'nam', 'weekend', '3+', 'Combo Kid'),
('Hài', 'sang', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'sang', 'tren_45', 'nam', 'weekend', '1', 'Combo Healthy'),
('Hành động', 'toi', '36_45', 'nam', 'weekend', '2', 'Combo Family'),
('Tình cảm', 'sang', '18_25', 'nam', 'weekend', '2', 'Combo Family'),
('Phiêu lưu', 'toi', 'tren_45', 'nu', 'weekday', '2', 'Combo Healthy'),
('Phiêu lưu', 'chieu', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Phiêu lưu', 'sang', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'chieu', '26_35', 'nam', 'weekend', '1', 'Combo Solo King'),
('Cổ Trang', 'sang', '18_25', 'nam', 'weekday', '1', 'Combo Standard'),
('Hoạt hình', 'chieu', '26_35', 'nu', 'weekend', '3+', 'Combo Standard'),
('Tình cảm', 'toi', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Tình cảm', 'toi', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'chieu', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'sang', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'chieu', 'duoi_18', 'nam', 'weekend', '1', 'Combo Kid'),
('Hoạt hình', 'toi', 'duoi_18', 'nam', 'weekend', '1', 'Combo Kid'),
('Tình cảm', 'chieu', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'sang', '26_35', 'nam', 'weekend', '1', 'Combo Standard'),
('Cổ Trang', 'sang', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Hành động', 'toi', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Phiêu lưu', 'sang', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Ca nhạc', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', 'tren_45', 'nu', 'weekday', '3+', 'Combo Healthy'),
('Phiêu lưu', 'sang', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Ngôn Tình', 'sang', '36_45', 'nam', 'weekday', '3+', 'Combo Standard'),
('Hài', 'toi', '36_45', 'nu', 'weekend', '1', 'Combo Standard'),
('Tình cảm', 'chieu', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'toi', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Tình cảm', 'chieu', '18_25', 'nam', 'weekend', '3+', 'Combo Standard'),
('Tình cảm', 'toi', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', '26_35', 'nam', 'weekend', '1', 'Combo Solo King'),
('Cổ Trang', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Kinh Dị', 'sang', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Phiêu lưu', 'sang', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'toi', 'duoi_18', 'nam', 'weekend', '2', 'Bắp rang bơ'),
('Tình cảm', 'sang', '36_45', 'nu', 'weekday', '3+', 'Combo Family'),
('Kinh Dị', 'toi', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Kinh Dị', 'toi', '26_35', 'nu', 'weekend', '3+', 'Combo Family'),
('Tình cảm', 'toi', '36_45', 'nam', 'weekend', '3+', 'Combo Family'),
('Hành động', 'toi', '36_45', 'nam', 'weekday', '1', 'Combo Solo King'),
('Phiêu lưu', 'toi', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Hoạt hình', 'chieu', '36_45', 'nu', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'chieu', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'chieu', 'tren_45', 'nu', 'weekend', '2', 'Combo Healthy'),
('Hoạt hình', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'toi', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Hành động', 'sang', '26_35', 'nu', 'weekend', '1', 'Bắp rang bơ'),
('Cổ Trang', 'toi', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl');

-- Batch 2: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Hài', 'sang', '18_25', 'nam', 'weekend', '1', 'Combo Standard'),
('Hoạt hình', 'chieu', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Ngôn Tình', 'toi', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'toi', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Tình cảm', 'toi', '36_45', 'nam', 'weekday', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'sang', 'tren_45', 'nam', 'weekend', '3+', 'Combo Healthy'),
('Khoa học viễn tưởng', 'sang', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Hoạt hình', 'chieu', 'duoi_18', 'nu', 'weekend', '1', 'Bắp rang bơ'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'sang', '26_35', 'nam', 'weekday', '1', 'Combo Standard'),
('Khoa học viễn tưởng', 'sang', 'duoi_18', 'nu', 'weekday', '3+', 'Combo Kid'),
('Hành động', 'chieu', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Hoạt hình', 'toi', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Ca nhạc', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Ca nhạc', 'chieu', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Phiêu lưu', 'toi', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Hành động', 'chieu', 'tren_45', 'nam', 'weekday', '2', 'Combo Healthy'),
('Ngôn Tình', 'sang', '36_45', 'nu', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'sang', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Cổ Trang', 'toi', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Phiêu lưu', 'chieu', '36_45', 'nam', 'weekend', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'toi', '26_35', 'nam', 'weekend', '2', 'Combo Couple'),
('Phiêu lưu', 'toi', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Hoạt hình', 'chieu', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Phiêu lưu', 'sang', '36_45', 'nam', 'weekday', '3+', 'Combo Family'),
('Tình cảm', 'chieu', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Kinh Dị', 'toi', '18_25', 'nam', 'weekday', '2', 'Combo Family'),
('Kinh Dị', 'chieu', '18_25', 'nu', 'weekend', '3+', 'Combo Standard'),
('Hành động', 'sang', 'duoi_18', 'nam', 'weekday', '3+', 'Combo Kid'),
('Kinh Dị', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Hành động', 'chieu', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Ngôn Tình', 'toi', '26_35', 'nam', 'weekend', '2', 'Combo Couple'),
('Cổ Trang', 'sang', '26_35', 'nam', 'weekday', '3+', 'Combo Standard'),
('Ngôn Tình', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'toi', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'sang', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'chieu', 'tren_45', 'nam', 'weekend', '2', 'Combo Healthy'),
('Hoạt hình', 'sang', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Hoạt hình', 'toi', 'tren_45', 'nu', 'weekend', '2', 'Combo Healthy'),
('Phiêu lưu', 'sang', '36_45', 'nam', 'weekend', '1', 'Combo Standard'),
('Cổ Trang', 'toi', 'duoi_18', 'nam', 'weekend', '2', 'Combo Kid'),
('Phiêu lưu', 'toi', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Hài', 'toi', 'tren_45', 'nu', 'weekend', '1', 'Combo Healthy'),
('Hoạt hình', 'sang', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'chieu', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Hoạt hình', 'sang', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'chieu', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Ngôn Tình', 'toi', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid');

-- Batch 3: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Hài', 'chieu', 'tren_45', 'nu', 'weekday', '3+', 'Combo Healthy'),
('Kinh Dị', 'toi', '18_25', 'nam', 'weekend', '1', 'Combo Solo King'),
('Hoạt hình', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'toi', 'tren_45', 'nam', 'weekend', '1', 'Combo Healthy'),
('Ca nhạc', 'toi', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'toi', 'tren_45', 'nam', 'weekday', '3+', 'Combo Healthy'),
('Ca nhạc', 'toi', 'duoi_18', 'nam', 'weekday', '3+', 'Combo Kid'),
('Khoa học viễn tưởng', 'toi', '26_35', 'nam', 'weekend', '2', 'Combo Couple'),
('Hành động', 'chieu', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Tình cảm', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Standard'),
('Hài', 'sang', '18_25', 'nam', 'weekday', '1', 'Combo Standard'),
('Cổ Trang', 'chieu', 'tren_45', 'nu', 'weekday', '3+', 'Combo Healthy'),
('Cổ Trang', 'sang', 'tren_45', 'nam', 'weekday', '3+', 'Combo Healthy'),
('Phiêu lưu', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Hoạt hình', 'sang', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Hành động', 'sang', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Phiêu lưu', 'chieu', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Ngôn Tình', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'sang', 'tren_45', 'nam', 'weekday', '3+', 'Combo Healthy'),
('Hài', 'chieu', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'toi', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'sang', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Ca nhạc', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'chieu', 'duoi_18', 'nu', 'weekday', '2', 'Bắp rang bơ'),
('Kinh Dị', 'toi', '26_35', 'nam', 'weekend', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'chieu', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'sang', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Hài', 'toi', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'chieu', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'toi', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Tình cảm', 'toi', 'duoi_18', 'nam', 'weekday', '3+', 'Combo Kid'),
('Hài', 'sang', 'duoi_18', 'nam', 'weekday', '2', 'Combo Kid'),
('Cổ Trang', 'toi', 'tren_45', 'nam', 'weekday', '2', 'Combo Standard'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Tình cảm', 'chieu', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Kinh Dị', 'sang', '18_25', 'nam', 'weekend', '1', 'Combo Solo King'),
('Khoa học viễn tưởng', 'chieu', '36_45', 'nam', 'weekend', '2', 'Combo Family'),
('Hài', 'sang', '26_35', 'nam', 'weekend', '3+', 'Combo Family'),
('Kinh Dị', 'chieu', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'chieu', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Ngôn Tình', 'toi', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nam', 'weekday', '2', 'Combo Family'),
('Hành động', 'toi', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'sang', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Hành động', 'chieu', '26_35', 'nu', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'toi', 'duoi_18', 'nam', 'weekday', '1', 'Bắp rang bơ'),
('Cổ Trang', 'toi', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Ngôn Tình', 'chieu', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl');

-- Batch 4: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Ca nhạc', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'toi', 'tren_45', 'nu', 'weekday', '1', 'Combo Healthy'),
('Tình cảm', 'chieu', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Hài', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'toi', '36_45', 'nu', 'weekend', '1', 'Combo Standard'),
('Khoa học viễn tưởng', 'toi', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'toi', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Kinh Dị', 'toi', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Hành động', 'toi', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'chieu', 'duoi_18', 'nam', 'weekend', '2', 'Combo Kid'),
('Cổ Trang', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Hành động', 'toi', 'tren_45', 'nam', 'weekend', '3+', 'Combo Healthy'),
('Tình cảm', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', 'duoi_18', 'nam', 'weekend', '1', 'Combo Kid'),
('Hành động', 'chieu', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Phiêu lưu', 'sang', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'toi', '26_35', 'nu', 'weekday', '3+', 'Combo Standard'),
('Cổ Trang', 'toi', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Hài', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', 'tren_45', 'nu', 'weekend', '1', 'Combo Healthy'),
('Hoạt hình', 'toi', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Ca nhạc', 'toi', '36_45', 'nam', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'toi', 'duoi_18', 'nam', 'weekday', '2', 'Combo Kid'),
('Khoa học viễn tưởng', 'chieu', '36_45', 'nu', 'weekday', '2', 'Combo Family'),
('Hành động', 'toi', '36_45', 'nam', 'weekend', '2', 'Combo Couple'),
('Hành động', 'toi', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'toi', 'tren_45', 'nu', 'weekday', '1', 'Combo Healthy'),
('Kinh Dị', 'sang', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Hài', 'toi', '36_45', 'nam', 'weekday', '3+', 'Combo Family'),
('Ngôn Tình', 'chieu', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Hoạt hình', 'sang', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Hài', 'toi', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'chieu', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Kinh Dị', 'toi', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Ngôn Tình', 'toi', 'duoi_18', 'nam', 'weekday', '2', 'Combo Kid'),
('Ngôn Tình', 'sang', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Tình cảm', 'chieu', '36_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Hành động', 'sang', '26_35', 'nam', 'weekend', '3+', 'Combo Family'),
('Ngôn Tình', 'sang', '36_45', 'nu', 'weekday', '3+', 'Combo Family'),
('Tình cảm', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'sang', 'duoi_18', 'nu', 'weekend', '3+', 'Combo Kid'),
('Kinh Dị', 'chieu', '18_25', 'nam', 'weekend', '1', 'Combo Solo King'),
('Ngôn Tình', 'sang', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Cổ Trang', 'chieu', 'tren_45', 'nu', 'weekday', '2', 'Combo Healthy'),
('Khoa học viễn tưởng', 'toi', 'duoi_18', 'nam', 'weekday', '2', 'Combo Kid'),
('Hoạt hình', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Family'),
('Kinh Dị', 'toi', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Kinh Dị', 'chieu', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Cổ Trang', 'sang', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid');

-- Batch 5: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Kinh Dị', 'sang', 'duoi_18', 'nam', 'weekday', '2', 'Combo Kid'),
('Phiêu lưu', 'toi', '36_45', 'nu', 'weekday', '3+', 'Combo Family'),
('Cổ Trang', 'chieu', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Tình cảm', 'toi', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Cổ Trang', 'sang', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Hành động', 'sang', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Kinh Dị', 'chieu', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Phiêu lưu', 'toi', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Cổ Trang', 'sang', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'sang', 'duoi_18', 'nu', 'weekday', '3+', 'Combo Kid'),
('Ngôn Tình', 'sang', 'duoi_18', 'nam', 'weekday', '2', 'Combo Kid'),
('Hoạt hình', 'sang', 'tren_45', 'nu', 'weekday', '1', 'Combo Healthy'),
('Phiêu lưu', 'chieu', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Phiêu lưu', 'chieu', '26_35', 'nu', 'weekday', '3+', 'Combo Family'),
('Ngôn Tình', 'sang', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Hành động', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Cổ Trang', 'chieu', '18_25', 'nam', 'weekday', '1', 'Combo Standard'),
('Hoạt hình', 'toi', '36_45', 'nu', 'weekend', '3+', 'Combo Family'),
('Ngôn Tình', 'sang', '18_25', 'nam', 'weekend', '1', 'Combo Standard'),
('Ngôn Tình', 'toi', '36_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Cổ Trang', 'toi', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'sang', 'tren_45', 'nu', 'weekday', '1', 'Combo Healthy'),
('Ngôn Tình', 'sang', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'sang', '36_45', 'nam', 'weekday', '3+', 'Combo Standard'),
('Phiêu lưu', 'toi', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Ngôn Tình', 'toi', 'tren_45', 'nam', 'weekday', '2', 'Combo Healthy'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Ca nhạc', 'sang', '26_35', 'nam', 'weekday', '1', 'Combo Standard'),
('Phiêu lưu', 'chieu', 'tren_45', 'nam', 'weekday', '2', 'Combo Healthy'),
('Cổ Trang', 'chieu', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Cổ Trang', 'toi', 'tren_45', 'nu', 'weekend', '2', 'Combo Healthy'),
('Tình cảm', 'toi', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Tình cảm', 'chieu', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Ca nhạc', 'toi', 'duoi_18', 'nam', 'weekday', '3+', 'Combo Kid'),
('Tình cảm', 'toi', 'tren_45', 'nam', 'weekday', '2', 'Combo Healthy'),
('Cổ Trang', 'chieu', '18_25', 'nu', 'weekday', '1', 'Bắp rang bơ'),
('Ngôn Tình', 'toi', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Tình cảm', 'toi', 'duoi_18', 'nam', 'weekday', '2', 'Bắp rang bơ'),
('Khoa học viễn tưởng', 'toi', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Hoạt hình', 'toi', 'duoi_18', 'nam', 'weekday', '1', 'Bắp rang bơ'),
('Phiêu lưu', 'chieu', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Tình cảm', 'sang', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Hài', 'sang', '18_25', 'nam', 'weekend', '1', 'Combo Standard'),
('Phiêu lưu', 'chieu', 'duoi_18', 'nam', 'weekend', '2', 'Combo Kid'),
('Ca nhạc', 'chieu', '36_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Khoa học viễn tưởng', 'sang', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Kinh Dị', 'chieu', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Hài', 'chieu', 'duoi_18', 'nam', 'weekend', '1', 'Combo Kid');

-- Batch 6: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Tình cảm', 'chieu', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Tình cảm', 'sang', '36_45', 'nam', 'weekend', '1', 'Combo Standard'),
('Ngôn Tình', 'chieu', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Ca nhạc', 'toi', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'chieu', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Kinh Dị', 'sang', '26_35', 'nu', 'weekday', '2', 'Combo Family'),
('Ngôn Tình', 'chieu', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Tình cảm', 'chieu', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Khoa học viễn tưởng', 'toi', '36_45', 'nam', 'weekend', '1', 'Combo Solo King'),
('Hài', 'chieu', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Cổ Trang', 'toi', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Ca nhạc', 'chieu', 'tren_45', 'nam', 'weekday', '1', 'Combo Healthy'),
('Hoạt hình', 'toi', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Hoạt hình', 'chieu', '26_35', 'nu', 'weekend', '2', 'Combo Family'),
('Hành động', 'sang', '26_35', 'nam', 'weekend', '2', 'Combo Couple'),
('Hành động', 'chieu', 'tren_45', 'nu', 'weekday', '1', 'Combo Healthy'),
('Ngôn Tình', 'sang', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'toi', 'tren_45', 'nam', 'weekday', '1', 'Combo Standard'),
('Cổ Trang', 'sang', '36_45', 'nam', 'weekend', '1', 'Combo Standard'),
('Khoa học viễn tưởng', 'toi', '26_35', 'nu', 'weekday', '3+', 'Combo Family'),
('Hoạt hình', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Family'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'sang', '18_25', 'nu', 'weekend', '2', 'Combo Family'),
('Hài', 'chieu', 'duoi_18', 'nam', 'weekend', '1', 'Combo Kid'),
('Kinh Dị', 'toi', '36_45', 'nam', 'weekday', '1', 'Combo Solo King'),
('Ca nhạc', 'sang', '26_35', 'nu', 'weekday', '3+', 'Combo Family'),
('Cổ Trang', 'chieu', 'duoi_18', 'nu', 'weekend', '1', 'Combo Kid'),
('Cổ Trang', 'sang', '18_25', 'nam', 'weekend', '2', 'Combo Family'),
('Tình cảm', 'chieu', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Cổ Trang', 'chieu', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Tình cảm', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'chieu', '36_45', 'nam', 'weekend', '2', 'Combo Couple'),
('Ca nhạc', 'chieu', '26_35', 'nam', 'weekday', '1', 'Combo Standard'),
('Hoạt hình', 'chieu', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Kinh Dị', 'sang', '18_25', 'nam', 'weekend', '1', 'Combo Solo King'),
('Hài', 'toi', '26_35', 'nu', 'weekday', '3+', 'Combo Standard'),
('Hành động', 'chieu', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Khoa học viễn tưởng', 'sang', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Ca nhạc', 'toi', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Tình cảm', 'chieu', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Ngôn Tình', 'chieu', '26_35', 'nu', 'weekend', '3+', 'Combo Family'),
('Hoạt hình', 'sang', 'duoi_18', 'nam', 'weekend', '1', 'Combo Kid'),
('Hài', 'toi', 'tren_45', 'nu', 'weekend', '2', 'Combo Healthy'),
('Hoạt hình', 'toi', '36_45', 'nu', 'weekend', '1', 'Combo Standard'),
('Phiêu lưu', 'chieu', '36_45', 'nam', 'weekday', '1', 'Combo Standard'),
('Cổ Trang', 'toi', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Cổ Trang', 'sang', '36_45', 'nu', 'weekend', '1', 'Combo Standard'),
('Hành động', 'toi', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Hành động', 'toi', '36_45', 'nu', 'weekday', '3+', 'Combo Family');

-- Batch 7: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Ngôn Tình', 'toi', '36_45', 'nu', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'chieu', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'sang', '36_45', 'nam', 'weekday', '1', 'Combo Standard'),
('Hành động', 'chieu', '26_35', 'nu', 'weekday', '3+', 'Combo Family'),
('Hài', 'toi', 'duoi_18', 'nu', 'weekday', '3+', 'Combo Kid'),
('Kinh Dị', 'sang', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'toi', '36_45', 'nam', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Hành động', 'sang', '26_35', 'nam', 'weekend', '1', 'Combo Solo King'),
('Ngôn Tình', 'chieu', '26_35', 'nam', 'weekday', '1', 'Combo Standard'),
('Hoạt hình', 'toi', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Hành động', 'chieu', '26_35', 'nu', 'weekend', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'sang', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Khoa học viễn tưởng', 'chieu', 'tren_45', 'nam', 'weekday', '3+', 'Combo Healthy'),
('Hoạt hình', 'sang', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'toi', '36_45', 'nam', 'weekend', '1', 'Combo Standard'),
('Cổ Trang', 'sang', 'tren_45', 'nu', 'weekend', '1', 'Combo Healthy'),
('Hành động', 'toi', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Kinh Dị', 'toi', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Kinh Dị', 'toi', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Hành động', 'chieu', 'duoi_18', 'nu', 'weekend', '3+', 'Combo Kid'),
('Hài', 'toi', 'duoi_18', 'nu', 'weekend', '1', 'Combo Kid'),
('Hài', 'sang', '36_45', 'nam', 'weekend', '2', 'Combo Couple'),
('Phiêu lưu', 'toi', '36_45', 'nu', 'weekend', '3+', 'Combo Family'),
('Phiêu lưu', 'toi', '36_45', 'nu', 'weekday', '2', 'Combo Couple'),
('Hài', 'sang', 'tren_45', 'nu', 'weekday', '2', 'Combo Healthy'),
('Khoa học viễn tưởng', 'toi', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Hành động', 'toi', '36_45', 'nu', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', 'tren_45', 'nu', 'weekday', '2', 'Combo Healthy'),
('Cổ Trang', 'toi', '18_25', 'nu', 'weekday', '1', 'Bắp rang bơ'),
('Ngôn Tình', 'sang', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Kinh Dị', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', '36_45', 'nam', 'weekday', '1', 'Combo Solo King'),
('Hành động', 'toi', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Family'),
('Tình cảm', 'toi', 'tren_45', 'nam', 'weekday', '3+', 'Combo Healthy'),
('Kinh Dị', 'toi', 'duoi_18', 'nu', 'weekday', '3+', 'Combo Kid'),
('Ca nhạc', 'toi', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Cổ Trang', 'toi', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Hài', 'toi', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Hành động', 'chieu', 'duoi_18', 'nu', 'weekend', '1', 'Combo Kid'),
('Hài', 'chieu', 'tren_45', 'nu', 'weekday', '1', 'Combo Healthy'),
('Kinh Dị', 'chieu', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Cổ Trang', 'sang', 'tren_45', 'nam', 'weekend', '2', 'Combo Healthy'),
('Phiêu lưu', 'chieu', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Cổ Trang', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Hài', 'toi', 'duoi_18', 'nu', 'weekend', '1', 'Combo Kid'),
('Hành động', 'chieu', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'toi', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Hành động', 'toi', '36_45', 'nu', 'weekday', '3+', 'Combo Family');

-- Batch 8: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Tình cảm', 'chieu', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Ngôn Tình', 'chieu', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Tình cảm', 'toi', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Ca nhạc', 'sang', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', '36_45', 'nu', 'weekend', '1', 'Combo Standard'),
('Phiêu lưu', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'toi', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Tình cảm', 'chieu', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Cổ Trang', 'sang', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Tình cảm', 'sang', '36_45', 'nam', 'weekend', '2', 'Combo Couple'),
('Phiêu lưu', 'toi', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Kinh Dị', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Ca nhạc', 'toi', '36_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Hoạt hình', 'toi', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Hoạt hình', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Family'),
('Phiêu lưu', 'toi', 'tren_45', 'nam', 'weekend', '2', 'Combo Healthy'),
('Tình cảm', 'toi', 'duoi_18', 'nu', 'weekend', '1', 'Combo Kid'),
('Ngôn Tình', 'toi', 'duoi_18', 'nu', 'weekday', '3+', 'Combo Kid'),
('Tình cảm', 'chieu', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'chieu', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'sang', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Ca nhạc', 'chieu', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Tình cảm', 'toi', 'tren_45', 'nu', 'weekday', '1', 'Combo Healthy'),
('Hành động', 'toi', '36_45', 'nu', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'sang', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Hành động', 'chieu', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Phiêu lưu', 'chieu', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Ca nhạc', 'toi', '18_25', 'nam', 'weekday', '1', 'Combo Standard'),
('Tình cảm', 'toi', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'chieu', '18_25', 'nam', 'weekday', '1', 'Combo Standard'),
('Hành động', 'toi', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nu', 'weekend', '2', 'Combo Family'),
('Cổ Trang', 'sang', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'sang', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Kinh Dị', 'chieu', 'duoi_18', 'nam', 'weekday', '2', 'Combo Kid'),
('Hoạt hình', 'chieu', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Tình cảm', 'sang', '36_45', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Phiêu lưu', 'sang', '26_35', 'nu', 'weekday', '3+', 'Combo Standard'),
('Hài', 'chieu', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Phiêu lưu', 'sang', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'toi', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Cổ Trang', 'sang', 'tren_45', 'nu', 'weekday', '1', 'Combo Healthy'),
('Cổ Trang', 'sang', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Phiêu lưu', 'toi', '18_25', 'nam', 'weekday', '1', 'Combo Standard'),
('Hài', 'chieu', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Hoạt hình', 'chieu', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Hoạt hình', 'chieu', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'chieu', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Hành động', 'chieu', 'duoi_18', 'nu', 'weekday', '3+', 'Combo Kid');

-- Batch 9: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Hoạt hình', 'chieu', 'tren_45', 'nu', 'weekday', '3+', 'Combo Healthy'),
('Hài', 'chieu', 'tren_45', 'nu', 'weekday', '3+', 'Combo Standard'),
('Hoạt hình', 'toi', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Ca nhạc', 'sang', '26_35', 'nam', 'weekday', '1', 'Combo Standard'),
('Phiêu lưu', 'chieu', '18_25', 'nu', 'weekday', '1', 'Bắp rang bơ'),
('Khoa học viễn tưởng', 'chieu', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Tình cảm', 'sang', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Kinh Dị', 'chieu', 'duoi_18', 'nu', 'weekday', '3+', 'Combo Kid'),
('Tình cảm', 'toi', '26_35', 'nu', 'weekday', '3+', 'Combo Family'),
('Tình cảm', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'toi', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Tình cảm', 'chieu', '18_25', 'nam', 'weekday', '1', 'Combo Standard'),
('Tình cảm', 'chieu', '36_45', 'nu', 'weekend', '3+', 'Combo Family'),
('Hài', 'sang', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Ngôn Tình', 'toi', '36_45', 'nam', 'weekday', '1', 'Combo Standard'),
('Hành động', 'toi', 'duoi_18', 'nam', 'weekend', '1', 'Bắp rang bơ'),
('Hành động', 'chieu', 'tren_45', 'nu', 'weekday', '3+', 'Combo Healthy'),
('Hoạt hình', 'chieu', '26_35', 'nam', 'weekday', '1', 'Combo Standard'),
('Hành động', 'toi', 'duoi_18', 'nu', 'weekday', '3+', 'Combo Kid'),
('Hành động', 'chieu', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'sang', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Phiêu lưu', 'toi', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Ngôn Tình', 'sang', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', '26_35', 'nu', 'weekend', '2', 'Combo Family'),
('Cổ Trang', 'toi', '36_45', 'nu', 'weekend', '1', 'Combo Standard'),
('Hài', 'toi', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Cổ Trang', 'toi', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Hài', 'chieu', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Hoạt hình', 'sang', '18_25', 'nam', 'weekend', '1', 'Combo Standard'),
('Ca nhạc', 'chieu', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Hành động', 'sang', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Kinh Dị', 'sang', 'duoi_18', 'nam', 'weekend', '1', 'Combo Kid'),
('Ca nhạc', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Hành động', 'chieu', 'duoi_18', 'nam', 'weekday', '3+', 'Combo Kid'),
('Khoa học viễn tưởng', 'sang', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Ngôn Tình', 'toi', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Hài', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Hành động', 'toi', 'duoi_18', 'nam', 'weekday', '3+', 'Combo Kid'),
('Phiêu lưu', 'toi', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'toi', 'tren_45', 'nu', 'weekday', '2', 'Combo Healthy'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'toi', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Khoa học viễn tưởng', 'toi', '26_35', 'nu', 'weekend', '3+', 'Combo Family'),
('Kinh Dị', 'toi', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Ngôn Tình', 'chieu', 'tren_45', 'nam', 'weekend', '3+', 'Combo Healthy'),
('Hành động', 'sang', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'toi', '18_25', 'nam', 'weekend', '1', 'Combo Solo King'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Ca nhạc', 'chieu', '26_35', 'nam', 'weekday', '1', 'Combo Standard'),
('Hoạt hình', 'chieu', 'tren_45', 'nu', 'weekend', '1', 'Combo Healthy');

-- Batch 10: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Kinh Dị', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', '26_35', 'nam', 'weekday', '3+', 'Combo Standard'),
('Kinh Dị', 'toi', '36_45', 'nam', 'weekend', '2', 'Combo Couple'),
('Hài', 'toi', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Ca nhạc', 'toi', '26_35', 'nu', 'weekday', '1', 'Bắp rang bơ'),
('Ngôn Tình', 'toi', 'tren_45', 'nam', 'weekend', '2', 'Combo Healthy'),
('Hài', 'toi', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'sang', '26_35', 'nu', 'weekday', '3+', 'Combo Standard'),
('Ca nhạc', 'chieu', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Phiêu lưu', 'chieu', 'tren_45', 'nam', 'weekday', '1', 'Combo Healthy'),
('Hoạt hình', 'sang', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'toi', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'chieu', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Phiêu lưu', 'toi', 'tren_45', 'nam', 'weekday', '2', 'Combo Healthy'),
('Tình cảm', 'sang', 'tren_45', 'nam', 'weekday', '3+', 'Combo Healthy'),
('Hài', 'toi', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Hài', 'sang', 'tren_45', 'nam', 'weekend', '2', 'Combo Healthy'),
('Hài', 'sang', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Hài', 'toi', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Khoa học viễn tưởng', 'chieu', 'tren_45', 'nam', 'weekend', '3+', 'Combo Healthy'),
('Kinh Dị', 'toi', '18_25', 'nu', 'weekend', '3+', 'Combo Standard'),
('Phiêu lưu', 'toi', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Phiêu lưu', 'toi', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Hài', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'chieu', '36_45', 'nam', 'weekday', '3+', 'Combo Family'),
('Hoạt hình', 'sang', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Ca nhạc', 'toi', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Phiêu lưu', 'sang', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Kinh Dị', 'toi', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Phiêu lưu', 'sang', 'tren_45', 'nam', 'weekend', '1', 'Combo Standard'),
('Ngôn Tình', 'toi', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Phiêu lưu', 'toi', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Hài', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'sang', '36_45', 'nam', 'weekend', '1', 'Combo Solo King'),
('Hành động', 'sang', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Hành động', 'chieu', 'duoi_18', 'nam', 'weekday', '2', 'Combo Kid'),
('Tình cảm', 'toi', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Ngôn Tình', 'chieu', 'tren_45', 'nu', 'weekend', '3+', 'Combo Standard'),
('Hành động', 'chieu', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'toi', 'tren_45', 'nu', 'weekend', '3+', 'Combo Healthy'),
('Cổ Trang', 'chieu', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'toi', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Phiêu lưu', 'chieu', 'tren_45', 'nam', 'weekday', '1', 'Combo Healthy'),
('Ngôn Tình', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Hài', 'sang', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Tình cảm', 'chieu', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Ca nhạc', 'sang', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Ca nhạc', 'sang', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Cổ Trang', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Couple');

-- Batch 11: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Hài', 'toi', '26_35', 'nu', 'weekday', '3+', 'Combo Family'),
('Ca nhạc', 'toi', 'duoi_18', 'nu', 'weekend', '1', 'Combo Kid'),
('Hài', 'chieu', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Kinh Dị', 'toi', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Hành động', 'toi', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Cổ Trang', 'toi', '18_25', 'nam', 'weekday', '2', 'Combo Family'),
('Ca nhạc', 'toi', '18_25', 'nam', 'weekend', '1', 'Combo Solo King'),
('Ca nhạc', 'toi', 'duoi_18', 'nu', 'weekday', '3+', 'Combo Kid'),
('Khoa học viễn tưởng', 'sang', 'duoi_18', 'nam', 'weekday', '3+', 'Combo Kid'),
('Ca nhạc', 'toi', '26_35', 'nu', 'weekday', '1', 'Bắp rang bơ'),
('Hài', 'toi', 'duoi_18', 'nam', 'weekend', '2', 'Combo Kid'),
('Hành động', 'sang', '36_45', 'nu', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'toi', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Hành động', 'chieu', 'tren_45', 'nu', 'weekday', '2', 'Combo Healthy'),
('Kinh Dị', 'toi', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Hoạt hình', 'toi', 'duoi_18', 'nam', 'weekday', '3+', 'Combo Kid'),
('Ngôn Tình', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'toi', 'tren_45', 'nam', 'weekday', '2', 'Combo Standard'),
('Tình cảm', 'chieu', '36_45', 'nu', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'chieu', '26_35', 'nam', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', '26_35', 'nam', 'weekend', '2', 'Combo Couple'),
('Hài', 'sang', '36_45', 'nu', 'weekend', '3+', 'Combo Family'),
('Hoạt hình', 'sang', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Kinh Dị', 'toi', 'tren_45', 'nu', 'weekday', '2', 'Combo Healthy'),
('Hành động', 'toi', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Tình cảm', 'chieu', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Hoạt hình', 'toi', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Hoạt hình', 'toi', 'duoi_18', 'nam', 'weekday', '3+', 'Combo Kid'),
('Ngôn Tình', 'chieu', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Ca nhạc', 'sang', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Hài', 'chieu', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', '36_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Ca nhạc', 'chieu', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Kinh Dị', 'toi', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'toi', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'chieu', '36_45', 'nam', 'weekday', '3+', 'Combo Standard'),
('Hoạt hình', 'sang', '26_35', 'nu', 'weekend', '2', 'Combo Family'),
('Hoạt hình', 'toi', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'toi', '36_45', 'nam', 'weekday', '1', 'Combo Standard'),
('Tình cảm', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Hài', 'chieu', 'tren_45', 'nu', 'weekday', '1', 'Combo Healthy'),
('Phiêu lưu', 'toi', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', '36_45', 'nam', 'weekend', '1', 'Combo Standard'),
('Ngôn Tình', 'chieu', '26_35', 'nam', 'weekend', '2', 'Combo Family'),
('Kinh Dị', 'toi', 'duoi_18', 'nam', 'weekday', '2', 'Combo Kid'),
('Ngôn Tình', 'sang', '26_35', 'nam', 'weekday', '1', 'Combo Standard'),
('Hoạt hình', 'toi', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Hài', 'toi', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'toi', '18_25', 'nu', 'weekend', '3+', 'Combo Standard');

-- Batch 12: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Ngôn Tình', 'toi', '36_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Hành động', 'chieu', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Tình cảm', 'toi', 'tren_45', 'nam', 'weekday', '1', 'Combo Healthy'),
('Hoạt hình', 'toi', '26_35', 'nu', 'weekday', '3+', 'Combo Family'),
('Ca nhạc', 'chieu', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'sang', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'sang', '18_25', 'nam', 'weekday', '2', 'Combo Family'),
('Tình cảm', 'toi', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Ca nhạc', 'chieu', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Kinh Dị', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Family'),
('Hoạt hình', 'toi', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Hành động', 'chieu', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'sang', '26_35', 'nu', 'weekday', '3+', 'Combo Family'),
('Kinh Dị', 'chieu', '18_25', 'nu', 'weekend', '2', 'Combo Family'),
('Hành động', 'chieu', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Phiêu lưu', 'chieu', 'tren_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Phiêu lưu', 'sang', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'chieu', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Hành động', 'sang', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'toi', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'toi', 'duoi_18', 'nam', 'weekend', '3+', 'Combo Kid'),
('Hành động', 'sang', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Phiêu lưu', 'sang', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Kinh Dị', 'toi', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Hành động', 'sang', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Hài', 'sang', '36_45', 'nu', 'weekend', '1', 'Combo Standard'),
('Ngôn Tình', 'sang', '18_25', 'nam', 'weekday', '1', 'Combo Standard'),
('Ngôn Tình', 'toi', 'duoi_18', 'nam', 'weekend', '3+', 'Combo Kid'),
('Cổ Trang', 'sang', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'sang', '26_35', 'nu', 'weekend', '3+', 'Combo Family'),
('Cổ Trang', 'chieu', '36_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Hài', 'chieu', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Hành động', 'toi', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'toi', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'chieu', '26_35', 'nam', 'weekend', '1', 'Combo Standard'),
('Cổ Trang', 'chieu', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Tình cảm', 'chieu', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'sang', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'toi', 'tren_45', 'nam', 'weekday', '3+', 'Combo Healthy'),
('Kinh Dị', 'toi', '36_45', 'nu', 'weekday', '3+', 'Combo Family'),
('Kinh Dị', 'toi', '26_35', 'nam', 'weekend', '3+', 'Combo Family'),
('Hoạt hình', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Tình cảm', 'sang', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'toi', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Tình cảm', 'toi', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Ngôn Tình', 'toi', '18_25', 'nam', 'weekend', '1', 'Combo Solo King'),
('Cổ Trang', 'toi', 'duoi_18', 'nam', 'weekend', '1', 'Combo Kid'),
('Hoạt hình', 'sang', '26_35', 'nam', 'weekday', '3+', 'Combo Family');

-- Batch 13: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Hành động', 'toi', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'chieu', '26_35', 'nam', 'weekend', '2', 'Combo Couple'),
('Hoạt hình', 'toi', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'sang', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'sang', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Phiêu lưu', 'sang', '18_25', 'nam', 'weekday', '1', 'Combo Standard'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Hoạt hình', 'sang', 'tren_45', 'nam', 'weekend', '2', 'Combo Healthy'),
('Khoa học viễn tưởng', 'chieu', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'sang', '36_45', 'nam', 'weekday', '1', 'Combo Standard'),
('Phiêu lưu', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Hành động', 'chieu', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Hoạt hình', 'toi', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Tình cảm', 'toi', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Hài', 'sang', 'duoi_18', 'nam', 'weekend', '3+', 'Combo Kid'),
('Ca nhạc', 'toi', '36_45', 'nu', 'weekend', '3+', 'Combo Family'),
('Hài', 'chieu', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'toi', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'toi', '26_35', 'nam', 'weekend', '2', 'Combo Couple'),
('Kinh Dị', 'toi', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Phiêu lưu', 'chieu', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Phiêu lưu', 'chieu', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'chieu', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'chieu', '36_45', 'nam', 'weekend', '2', 'Combo Couple'),
('Ca nhạc', 'chieu', '36_45', 'nu', 'weekend', '3+', 'Combo Family'),
('Hoạt hình', 'sang', '26_35', 'nam', 'weekday', '1', 'Combo Standard'),
('Cổ Trang', 'chieu', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Hoạt hình', 'chieu', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Hành động', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'chieu', 'tren_45', 'nu', 'weekend', '2', 'Combo Healthy'),
('Ca nhạc', 'chieu', 'tren_45', 'nam', 'weekday', '1', 'Combo Standard'),
('Kinh Dị', 'sang', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'toi', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'chieu', 'duoi_18', 'nu', 'weekday', '3+', 'Combo Kid'),
('Hoạt hình', 'toi', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'chieu', 'tren_45', 'nam', 'weekend', '1', 'Combo Healthy'),
('Hài', 'toi', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Hài', 'chieu', '36_45', 'nam', 'weekend', '3+', 'Combo Family'),
('Cổ Trang', 'sang', 'tren_45', 'nam', 'weekday', '2', 'Combo Healthy'),
('Hài', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'toi', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Hoạt hình', 'chieu', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Ngôn Tình', 'chieu', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'toi', 'duoi_18', 'nu', 'weekday', '3+', 'Combo Kid'),
('Ngôn Tình', 'sang', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Tình cảm', 'sang', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Ngôn Tình', 'chieu', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Hoạt hình', 'sang', '26_35', 'nam', 'weekend', '1', 'Combo Standard'),
('Hành động', 'chieu', '18_25', 'nam', 'weekend', '2', 'Combo Couple');

-- Batch 14: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Ca nhạc', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Family'),
('Kinh Dị', 'chieu', 'tren_45', 'nu', 'weekend', '1', 'Combo Healthy'),
('Ca nhạc', 'chieu', 'duoi_18', 'nu', 'weekday', '3+', 'Combo Kid'),
('Ca nhạc', 'toi', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Tình cảm', 'sang', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'toi', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Ca nhạc', 'chieu', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'sang', '36_45', 'nam', 'weekday', '1', 'Combo Standard'),
('Hoạt hình', 'chieu', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'toi', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'chieu', '18_25', 'nam', 'weekend', '1', 'Combo Standard'),
('Hài', 'sang', '36_45', 'nam', 'weekday', '1', 'Combo Standard'),
('Cổ Trang', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'chieu', 'tren_45', 'nu', 'weekend', '2', 'Combo Healthy'),
('Hài', 'toi', '36_45', 'nam', 'weekday', '3+', 'Combo Family'),
('Kinh Dị', 'sang', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Kinh Dị', 'toi', 'duoi_18', 'nu', 'weekend', '1', 'Bắp rang bơ'),
('Tình cảm', 'toi', '26_35', 'nam', 'weekend', '2', 'Combo Couple'),
('Hoạt hình', 'toi', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Tình cảm', 'sang', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Kinh Dị', 'toi', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Tình cảm', 'chieu', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Hành động', 'chieu', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Hài', 'sang', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Tình cảm', 'sang', '18_25', 'nam', 'weekend', '2', 'Combo Family'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Cổ Trang', 'toi', '26_35', 'nu', 'weekend', '1', 'Bắp rang bơ'),
('Cổ Trang', 'sang', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Ca nhạc', 'chieu', '36_45', 'nu', 'weekday', '3+', 'Combo Family'),
('Tình cảm', 'chieu', '36_45', 'nu', 'weekend', '3+', 'Combo Family'),
('Hài', 'sang', '36_45', 'nam', 'weekend', '3+', 'Combo Standard'),
('Tình cảm', 'sang', '36_45', 'nam', 'weekend', '2', 'Combo Couple'),
('Kinh Dị', 'toi', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Ngôn Tình', 'toi', '36_45', 'nam', 'weekend', '2', 'Combo Couple'),
('Ca nhạc', 'chieu', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'toi', 'tren_45', 'nam', 'weekday', '2', 'Combo Healthy'),
('Ca nhạc', 'chieu', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Khoa học viễn tưởng', 'toi', 'tren_45', 'nam', 'weekend', '3+', 'Combo Healthy'),
('Hài', 'chieu', '18_25', 'nam', 'weekend', '1', 'Combo Standard'),
('Hoạt hình', 'chieu', 'tren_45', 'nu', 'weekday', '2', 'Combo Healthy'),
('Hoạt hình', 'toi', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Cổ Trang', 'toi', '26_35', 'nam', 'weekday', '1', 'Combo Standard'),
('Hoạt hình', 'toi', '18_25', 'nu', 'weekday', '1', 'Bắp rang bơ'),
('Hài', 'toi', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'toi', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Kinh Dị', 'toi', 'tren_45', 'nam', 'weekend', '1', 'Combo Healthy'),
('Khoa học viễn tưởng', 'chieu', 'tren_45', 'nu', 'weekend', '1', 'Combo Healthy');

-- Batch 15: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Khoa học viễn tưởng', 'toi', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Hoạt hình', 'chieu', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Ngôn Tình', 'chieu', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Hoạt hình', 'toi', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Hài', 'toi', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Cổ Trang', 'sang', '36_45', 'nu', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'chieu', '36_45', 'nu', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'chieu', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Cổ Trang', 'toi', '36_45', 'nam', 'weekend', '1', 'Combo Standard'),
('Phiêu lưu', 'sang', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Hoạt hình', 'toi', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'sang', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Kinh Dị', 'sang', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'sang', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Hoạt hình', 'toi', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Khoa học viễn tưởng', 'chieu', '26_35', 'nu', 'weekday', '3+', 'Combo Family'),
('Ngôn Tình', 'toi', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Hoạt hình', 'chieu', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Kinh Dị', 'toi', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Ngôn Tình', 'chieu', 'tren_45', 'nam', 'weekday', '1', 'Combo Standard'),
('Ngôn Tình', 'toi', 'tren_45', 'nam', 'weekday', '2', 'Combo Healthy'),
('Kinh Dị', 'sang', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'chieu', 'duoi_18', 'nam', 'weekend', '2', 'Combo Kid'),
('Cổ Trang', 'toi', 'duoi_18', 'nam', 'weekday', '2', 'Bắp rang bơ'),
('Ca nhạc', 'toi', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Hành động', 'toi', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'chieu', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Khoa học viễn tưởng', 'toi', 'tren_45', 'nu', 'weekday', '2', 'Combo Healthy'),
('Kinh Dị', 'toi', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Kinh Dị', 'sang', '26_35', 'nam', 'weekend', '3+', 'Combo Family'),
('Kinh Dị', 'toi', 'duoi_18', 'nam', 'weekend', '1', 'Combo Kid'),
('Ca nhạc', 'toi', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Cổ Trang', 'sang', '36_45', 'nam', 'weekday', '3+', 'Combo Family'),
('Cổ Trang', 'chieu', '18_25', 'nam', 'weekday', '1', 'Combo Standard'),
('Ngôn Tình', 'sang', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'chieu', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Ca nhạc', 'chieu', '36_45', 'nu', 'weekday', '3+', 'Combo Family'),
('Ca nhạc', 'chieu', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Hài', 'chieu', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Hành động', 'chieu', '36_45', 'nam', 'weekday', '1', 'Combo Solo King'),
('Hành động', 'toi', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Tình cảm', 'chieu', '26_35', 'nam', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', 'tren_45', 'nam', 'weekday', '1', 'Combo Healthy'),
('Hài', 'chieu', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Kinh Dị', 'sang', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Hoạt hình', 'toi', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Cổ Trang', 'chieu', 'duoi_18', 'nu', 'weekend', '3+', 'Combo Kid');

-- Batch 16: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Khoa học viễn tưởng', 'toi', 'duoi_18', 'nam', 'weekday', '2', 'Combo Kid'),
('Khoa học viễn tưởng', 'chieu', '26_35', 'nam', 'weekend', '1', 'Combo Standard'),
('Khoa học viễn tưởng', 'chieu', '26_35', 'nam', 'weekend', '1', 'Combo Solo King'),
('Cổ Trang', 'toi', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Kinh Dị', 'sang', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'chieu', 'duoi_18', 'nam', 'weekend', '1', 'Combo Kid'),
('Kinh Dị', 'sang', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Cổ Trang', 'toi', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Cổ Trang', 'sang', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Hoạt hình', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Cổ Trang', 'chieu', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Hài', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'sang', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Ngôn Tình', 'chieu', 'duoi_18', 'nam', 'weekend', '3+', 'Combo Kid'),
('Ngôn Tình', 'toi', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Khoa học viễn tưởng', 'sang', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Hành động', 'toi', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Hài', 'toi', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Cổ Trang', 'chieu', 'duoi_18', 'nam', 'weekend', '1', 'Combo Kid'),
('Hành động', 'chieu', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Kinh Dị', 'sang', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'chieu', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Tình cảm', 'chieu', '36_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Tình cảm', 'toi', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Tình cảm', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'chieu', '26_35', 'nu', 'weekend', '2', 'Combo Family'),
('Kinh Dị', 'sang', '36_45', 'nam', 'weekend', '2', 'Combo Family'),
('Phiêu lưu', 'toi', '36_45', 'nu', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'chieu', '18_25', 'nam', 'weekend', '1', 'Combo Standard'),
('Hoạt hình', 'toi', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', '26_35', 'nam', 'weekend', '1', 'Combo Solo King'),
('Cổ Trang', 'sang', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'toi', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Ngôn Tình', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Hài', 'sang', '18_25', 'nam', 'weekday', '3+', 'Combo Standard'),
('Phiêu lưu', 'chieu', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'chieu', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Tình cảm', 'chieu', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Kinh Dị', 'toi', 'tren_45', 'nam', 'weekday', '2', 'Combo Healthy'),
('Cổ Trang', 'toi', '36_45', 'nam', 'weekend', '2', 'Combo Couple'),
('Hài', 'chieu', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Cổ Trang', 'chieu', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Phiêu lưu', 'chieu', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', '36_45', 'nam', 'weekend', '1', 'Combo Standard'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nam', 'weekend', '3+', 'Combo Standard'),
('Ca nhạc', 'chieu', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Ca nhạc', 'sang', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Hài', 'sang', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Hoạt hình', 'toi', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'toi', '26_35', 'nam', 'weekend', '2', 'Combo Couple');

-- Batch 17: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Cổ Trang', 'toi', '26_35', 'nam', 'weekend', '1', 'Combo Standard'),
('Tình cảm', 'sang', 'tren_45', 'nu', 'weekday', '1', 'Combo Healthy'),
('Hài', 'chieu', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Hoạt hình', 'sang', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Cổ Trang', 'chieu', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Hành động', 'toi', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Ca nhạc', 'sang', '26_35', 'nam', 'weekend', '1', 'Combo Standard'),
('Hoạt hình', 'chieu', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'sang', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'sang', 'duoi_18', 'nam', 'weekday', '3+', 'Bắp rang bơ'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nu', 'weekend', '1', 'Bắp rang bơ'),
('Khoa học viễn tưởng', 'toi', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Cổ Trang', 'chieu', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'sang', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Hành động', 'chieu', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Hành động', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'sang', '36_45', 'nu', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'sang', '36_45', 'nam', 'weekday', '1', 'Combo Standard'),
('Tình cảm', 'toi', 'tren_45', 'nu', 'weekday', '2', 'Combo Healthy'),
('Tình cảm', 'chieu', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Hài', 'chieu', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Cổ Trang', 'sang', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'toi', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Cổ Trang', 'toi', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Hành động', 'toi', '36_45', 'nam', 'weekend', '3+', 'Combo Family'),
('Kinh Dị', 'sang', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Kinh Dị', 'toi', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Cổ Trang', 'sang', '18_25', 'nam', 'weekday', '1', 'Combo Standard'),
('Ngôn Tình', 'toi', '36_45', 'nu', 'weekday', '2', 'Combo Family'),
('Hài', 'toi', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'toi', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Hoạt hình', 'toi', '36_45', 'nam', 'weekend', '3+', 'Combo Family'),
('Hành động', 'chieu', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'toi', '36_45', 'nam', 'weekday', '2', 'Combo Couple'),
('Hài', 'sang', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Kinh Dị', 'chieu', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'toi', '18_25', 'nu', 'weekend', '3+', 'Combo Standard'),
('Hoạt hình', 'chieu', 'duoi_18', 'nu', 'weekday', '3+', 'Combo Kid'),
('Phiêu lưu', 'toi', '18_25', 'nam', 'weekend', '3+', 'Combo Standard'),
('Ngôn Tình', 'sang', '36_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Hoạt hình', 'sang', '26_35', 'nam', 'weekday', '1', 'Combo Standard'),
('Hành động', 'chieu', '26_35', 'nam', 'weekday', '1', 'Combo Standard'),
('Ca nhạc', 'chieu', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Hài', 'toi', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Tình cảm', 'chieu', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Hoạt hình', 'sang', '26_35', 'nu', 'weekday', '1', 'Bắp rang bơ'),
('Hành động', 'toi', '26_35', 'nam', 'weekend', '3+', 'Combo Family');

-- Batch 18: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Hành động', 'toi', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Hoạt hình', 'chieu', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Hoạt hình', 'toi', 'tren_45', 'nam', 'weekend', '2', 'Combo Healthy'),
('Hài', 'sang', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Cổ Trang', 'sang', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Hoạt hình', 'chieu', '26_35', 'nam', 'weekend', '1', 'Combo Standard'),
('Hài', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Kinh Dị', 'sang', 'tren_45', 'nam', 'weekday', '1', 'Combo Healthy'),
('Ca nhạc', 'chieu', '36_45', 'nam', 'weekend', '1', 'Combo Standard'),
('Ngôn Tình', 'toi', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Kinh Dị', 'chieu', 'tren_45', 'nu', 'weekday', '1', 'Combo Healthy'),
('Hành động', 'chieu', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Cổ Trang', 'chieu', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Hành động', 'chieu', '26_35', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Ca nhạc', 'chieu', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Tình cảm', 'sang', '36_45', 'nu', 'weekday', '2', 'Combo Couple'),
('Hài', 'chieu', '36_45', 'nam', 'weekend', '1', 'Combo Solo King'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'chieu', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Tình cảm', 'toi', '18_25', 'nu', 'weekday', '3+', 'Combo Standard'),
('Hài', 'toi', '26_35', 'nu', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'sang', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nam', 'weekday', '2', 'Combo Family'),
('Hài', 'sang', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Ca nhạc', 'sang', '26_35', 'nam', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'toi', 'tren_45', 'nam', 'weekend', '3+', 'Combo Healthy'),
('Ca nhạc', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'toi', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Cổ Trang', 'chieu', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'sang', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Cổ Trang', 'sang', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Phiêu lưu', 'toi', 'duoi_18', 'nam', 'weekday', '2', 'Combo Kid'),
('Ngôn Tình', 'chieu', '36_45', 'nu', 'weekend', '1', 'Combo Standard'),
('Kinh Dị', 'sang', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Cổ Trang', 'toi', '36_45', 'nu', 'weekend', '1', 'Combo Standard'),
('Hài', 'chieu', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'sang', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'toi', '18_25', 'nam', 'weekend', '3+', 'Combo Standard'),
('Hành động', 'sang', '26_35', 'nu', 'weekend', '1', 'Bắp rang bơ'),
('Phiêu lưu', 'chieu', '36_45', 'nu', 'weekday', '3+', 'Combo Family'),
('Hài', 'sang', '26_35', 'nu', 'weekend', '3+', 'Combo Family'),
('Ngôn Tình', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Tình cảm', 'toi', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'toi', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Hành động', 'toi', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Cổ Trang', 'toi', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'sang', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'chieu', '18_25', 'nu', 'weekend', '2', 'Combo Couple');

-- Batch 19: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Phiêu lưu', 'chieu', '26_35', 'nu', 'weekday', '3+', 'Combo Family'),
('Kinh Dị', 'sang', '36_45', 'nam', 'weekday', '3+', 'Combo Family'),
('Ngôn Tình', 'sang', 'tren_45', 'nu', 'weekday', '2', 'Combo Healthy'),
('Ngôn Tình', 'toi', '36_45', 'nam', 'weekend', '1', 'Combo Standard'),
('Hành động', 'chieu', '26_35', 'nam', 'weekend', '1', 'Combo Solo King'),
('Tình cảm', 'toi', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Kinh Dị', 'sang', 'tren_45', 'nam', 'weekday', '3+', 'Combo Healthy'),
('Hài', 'toi', 'tren_45', 'nam', 'weekend', '1', 'Combo Healthy'),
('Ca nhạc', 'sang', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Khoa học viễn tưởng', 'sang', '26_35', 'nu', 'weekend', '2', 'Combo Couple'),
('Cổ Trang', 'toi', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'chieu', '36_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Ngôn Tình', 'toi', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Hoạt hình', 'sang', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Cổ Trang', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Cổ Trang', 'chieu', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'chieu', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Ca nhạc', 'toi', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'chieu', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Hoạt hình', 'toi', '18_25', 'nu', 'weekend', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'sang', 'tren_45', 'nam', 'weekday', '2', 'Combo Healthy'),
('Hoạt hình', 'chieu', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Hành động', 'chieu', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'toi', '26_35', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Tình cảm', 'toi', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', '26_35', 'nam', 'weekday', '3+', 'Combo Family'),
('Ngôn Tình', 'chieu', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Phiêu lưu', 'chieu', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Hành động', 'toi', '18_25', 'nu', 'weekend', '3+', 'Combo Standard'),
('Ngôn Tình', 'sang', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'chieu', '26_35', 'nam', 'weekday', '2', 'Combo Family'),
('Phiêu lưu', 'sang', 'tren_45', 'nu', 'weekday', '1', 'Combo Healthy'),
('Phiêu lưu', 'chieu', 'tren_45', 'nu', 'weekday', '2', 'Combo Standard'),
('Hoạt hình', 'toi', 'duoi_18', 'nu', 'weekend', '2', 'Bắp rang bơ'),
('Kinh Dị', 'toi', '36_45', 'nam', 'weekday', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'sang', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'toi', 'duoi_18', 'nam', 'weekend', '1', 'Combo Kid'),
('Ngôn Tình', 'sang', '36_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Hoạt hình', 'toi', 'duoi_18', 'nam', 'weekday', '2', 'Combo Kid'),
('Phiêu lưu', 'chieu', 'tren_45', 'nam', 'weekend', '3+', 'Combo Healthy'),
('Hành động', 'chieu', '26_35', 'nam', 'weekend', '2', 'Combo Couple'),
('Ca nhạc', 'sang', 'duoi_18', 'nam', 'weekday', '3+', 'Combo Kid'),
('Kinh Dị', 'sang', '36_45', 'nam', 'weekday', '1', 'Combo Solo King'),
('Khoa học viễn tưởng', 'sang', 'duoi_18', 'nu', 'weekday', '2', 'Combo Kid'),
('Hành động', 'toi', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Tình cảm', 'toi', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Hành động', 'toi', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Hài', 'sang', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl');

-- Batch 20: Mô phỏng phân phối đa dạng các nhóm khán giả
INSERT INTO `combo_training_data` (`the_loai`, `gio_chieu`, `khoang_tuoi`, `gioi_tinh`, `thu_trong_tuan`, `so_ghe`, `combo_chon`) VALUES
('Kinh Dị', 'chieu', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Ngôn Tình', 'toi', '18_25', 'nam', 'weekend', '1', 'Combo Standard'),
('Tình cảm', 'chieu', '36_45', 'nam', 'weekend', '3+', 'Combo Family'),
('Kinh Dị', 'sang', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Khoa học viễn tưởng', 'chieu', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Cổ Trang', 'sang', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'toi', '18_25', 'nu', 'weekend', '2', 'Combo Family'),
('Kinh Dị', 'chieu', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Cổ Trang', 'chieu', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Ngôn Tình', 'chieu', '18_25', 'nam', 'weekday', '2', 'Combo Couple'),
('Phiêu lưu', 'chieu', 'duoi_18', 'nu', 'weekend', '3+', 'Combo Kid'),
('Hành động', 'chieu', '36_45', 'nam', 'weekday', '3+', 'Combo Family'),
('Kinh Dị', 'chieu', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Hài', 'chieu', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Khoa học viễn tưởng', 'chieu', 'duoi_18', 'nam', 'weekend', '2', 'Combo Kid'),
('Kinh Dị', 'sang', '26_35', 'nam', 'weekday', '2', 'Combo Couple'),
('Hoạt hình', 'chieu', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Ngôn Tình', 'chieu', '36_45', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Hoạt hình', 'chieu', 'tren_45', 'nu', 'weekend', '2', 'Combo Healthy'),
('Phiêu lưu', 'toi', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Cổ Trang', 'toi', '36_45', 'nu', 'weekend', '1', 'Combo Standard'),
('Hoạt hình', 'toi', '36_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Khoa học viễn tưởng', 'toi', 'duoi_18', 'nu', 'weekend', '2', 'Combo Kid'),
('Hành động', 'sang', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Ngôn Tình', 'chieu', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Hành động', 'sang', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Ngôn Tình', 'chieu', '18_25', 'nam', 'weekend', '2', 'Combo Couple'),
('Hoạt hình', 'toi', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Phiêu lưu', 'toi', 'duoi_18', 'nu', 'weekday', '1', 'Combo Kid'),
('Phiêu lưu', 'chieu', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Ca nhạc', 'toi', '18_25', 'nam', 'weekday', '1', 'Combo Solo King'),
('Khoa học viễn tưởng', 'toi', '18_25', 'nu', 'weekend', '3+', 'Combo Family'),
('Kinh Dị', 'chieu', '18_25', 'nam', 'weekend', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'chieu', 'tren_45', 'nu', 'weekday', '3+', 'Combo Healthy'),
('Ca nhạc', 'toi', 'tren_45', 'nam', 'weekday', '3+', 'Combo Standard'),
('Kinh Dị', 'chieu', '18_25', 'nu', 'weekday', '1', 'Combo Sweet Girl'),
('Kinh Dị', 'chieu', '36_45', 'nam', 'weekend', '3+', 'Combo Family'),
('Phiêu lưu', 'chieu', '18_25', 'nu', 'weekday', '3+', 'Combo Family'),
('Phiêu lưu', 'toi', '26_35', 'nu', 'weekday', '2', 'Combo Couple'),
('Kinh Dị', 'chieu', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Hài', 'sang', '18_25', 'nam', 'weekday', '1', 'Combo Standard'),
('Hài', 'chieu', 'duoi_18', 'nam', 'weekday', '1', 'Combo Kid'),
('Cổ Trang', 'chieu', '18_25', 'nam', 'weekday', '3+', 'Combo Family'),
('Khoa học viễn tưởng', 'chieu', '26_35', 'nam', 'weekday', '1', 'Combo Solo King'),
('Ca nhạc', 'chieu', '18_25', 'nu', 'weekend', '1', 'Combo Sweet Girl'),
('Hài', 'sang', '18_25', 'nu', 'weekday', '2', 'Combo Couple'),
('Ca nhạc', 'toi', '36_45', 'nu', 'weekend', '2', 'Combo Couple'),
('Ca nhạc', 'chieu', '36_45', 'nu', 'weekday', '1', 'Combo Standard'),
('Hành động', 'toi', 'tren_45', 'nu', 'weekday', '2', 'Combo Healthy'),
('Phiêu lưu', 'toi', '26_35', 'nam', 'weekday', '1', 'Combo Solo King');

